version: '3.7'

services:

  # DataStax Enterprise with Vector Search
  # Just one node for prototyping purposes
  seed_node:
    image: "datastax/dse-server:7.0.0-alpha.4"
    environment:
      - DS_LICENSE=accept
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    volumes:
      - ./seed_data:/var/lib/cassandra
    ports:
      - 9042:9042